on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: gradle wrapper --gradle-version 6.6.1 --distribution-type all
      - run: ./gradlew dist
      - run: ./gradlew tests
